name = "caps-image-proxy"
main = "caps-image-proxy.js"
compatibility_date = "2024-01-01"

# Production
[env.production]
name = "caps-image-proxy"
route = { pattern = "images.make-page.com/*", zone_name = "make-page.com" }

# Custom domain
workers_dev = false
