name = "posting-generator"
main = "posting-generator.js"
compatibility_date = "2024-01-01"
account_id = "73506724e3c7dd97bc939983761a90cf"

[vars]
SHEETS_ID = "1KrzLFi8Wt9GTGT97gcMoXnbZ3OJ04NsP4lncJyIdyhU"

# Secret (GitHub Actions에서 설정)
# GOOGLE_SERVICE_ACCOUNT_JSON: Service Account JSON
